apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-deployment
  namespace: poc
  labels:
    app: poc-deployment
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: poc-api
  template:
    metadata:
      labels:
        component: poc-api
      annotations:
        vault.hashicorp.com/role: 'poc-sa-poc'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/auth-path: 'auth/sahab2-security-dev'
        vault.hashicorp.com/agent-inject-secret-config: 'sahab2-kv/poc-secret'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "sahab2-kv/poc-secret" -}} 
            export SECRET="{{ .Data.data.key }}"
          {{- end }}
    spec:
      serviceAccountName: poc-sa
      containers:
        - name: poc-api
          image: canpolatoral/vault-injector-poc:0.1
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args:
            ['-c', 'source /vault/secrets/config && dotnet VaultInjectorPOC.dll']
          ports:
            - containerPort: 80